langage: go
sudo: required
go:
  - 1.5
  - tip
install:
  - export GOPATH=${HOME}/gopath
  - go get github.com/aws/aws-sdk-go/service/sns
  - go get github.com/robfig/cron
  - go get gopkg.in/gcfg.v1
  - go get -d -t -v ./...
  - go build -v ./...
script:
  - go vet ./...
  - go test -v ./...
